### PR TITLE
Fixed several things

### PR DESCRIPTION
**Pull request by sebastiaanspeck**
- Fixed some issues in soccer.py
- Made the tests succeed: [Travis](https://travis-ci.com/sebastiaanspeck/sportmonks)

### CODE REVIEW

**Comment by sebastiaanspeck** [comment]
Great! I made some more changes. See [sportmonks_v2](https://github.com/sebastiaanspeck/sportmonks_v2). Some endpoints weren't implemented

**Comment by sebastiaanspeck** [comment]
Any update on this?

**Comment by Dmitrii-I** [comment]
@sebastiaanspeck Sorry that it took so long... Basically I had to do some yak shaving... From now on I should be able to reply much faster.

I do not agree with some of your changes. For example renaming to sportmonks_v2. Are you ok if I cherry pick your changes or is this PR all-or-nothing?

**Comment by sebastiaanspeck** [comment]
Cherry-picking is allowed

**Pull request closed without merging**
